name: 'Add release channel'
description: 'Add a release channel to your package.json version'
inputs:
  channel:
    description: 'name of the channel you wanna add'
    required: true
    default: 'alpha'
  buildNumber:
    description: 'add the build number to your release'
    required: false
    default: null
  monorepo:
    description: 'boolean flag to indicate if you're using monorepo or not 
    required: false
    default: null   
outputs:
  release_channel:
    description: 'Complete release channel'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pokemon_id}}
