name: test release channel action

on: push

jobs:
  test-add-release-channel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: Use our release channel action
      uses: felix-schaipp/add-release-channel@main
      id: version
      with:
        channel: 'alpha'
        buildNumber: 1807022021 # hhddmmyyyy
    - name: Check if the release channel was correctly set
      run: |
        echo "${{ steps.version.outputs.version }}"
        echo "${{ steps.version.outputs.buildNumber }}"
