name: test release channel action

on: push

jobs:
  test-add-release-channel:
    runs-on: ubuntu-latest
    name: Test adding a release channel locally
    steps:
    - uses: actions/checkout@v2 
    - name: Use our release channel action
      uses: felix-schaipp/add-release-channel@main
      id: channel
      with:
        channel: 'alpha'
        buildNumber: $(date +'%H%d%m%Y') # hhddmmyyyy
    - name: Check if the release channel was correctly set
      run: |
        echo "${{ steps.channel.outputs.release_channel }}"
        echo "${{ steps.channel.outputs.buildNumber }}"
        echo "${{ steps.channel.outputs.monorepo }}"
